---

- name: Add repo.mysql.com apt key
  apt_key:
    url: http://repo.mysql.com/RPM-GPG-KEY-mysql-2022
    state: present

- block:
    - name: Add wily repo for mysql-server-5.6
      apt_repository:
        repo: "deb http://repo.mysql.com/apt/ubuntu/ wily mysql-5.6"
        state: present
    - name: Pin Priority for repo.mysql.com
      copy:
        content: |
          Package: *
          Pin: origin "repo.mysql.com"
          Pin-Priority: 999
        dest: /etc/apt/preferences.d/mysql
  when: mysql_5_6

- name: Check if MySQL is already installed.
  stat: path=/etc/init.d/{{ mysql_daemon }}
  register: mysql_installed

- name: Update apt cache if MySQL is not yet installed.
  apt: update_cache=yes
  changed_when: False
  when: not mysql_installed.stat.exists

- name: Ensure MySQL Python libraries are installed.
  apt:
    name: "{{ mysql_python_package_debian }}"
    state: present

- name: Ensure MySQL packages are installed.
  apt:
    name: "{{ mysql_packages }}"
    state: present
  register: deb_mysql_install_packages

# Because Ubuntu starts MySQL as part of the install process, we need to stop
# mysql and remove the logfiles in case the user set a custom log file size.
- name: Ensure MySQL is stopped after initial install.
  service: "name={{ mysql_daemon }} state=stopped"
  when: not mysql_installed.stat.exists

- name: Delete innodb log files created by apt package after initial install.
  file: path={{ mysql_datadir }}/{{ item }} state=absent
  with_items:
    - ib_logfile0
    - ib_logfile1
  when: not mysql_installed.stat.exists
